;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Global WIN0

Global Text_0, Image_1, Container_0, Text_1, Text_1_Copy1, Text_1, Text_1_Copy1, Container_0, Text_1, Text_1_Copy1, Container_0, Text_1, Text_1_Copy1, Container_0, Text_1, Text_1_Copy1, Container_0

Global Img_WIN0_0

UseJPEGImageDecoder()

Img_WIN0_0 = LoadImage(#PB_Any,"C:\git\balancer\source\Loader-2\logo.jpg")
ResizeImage(Img_WIN0_0, 480,100)

Enumeration FormFont
  #Font_WIN0_0
  #Font_WIN0_1
  #Font_WIN0_2
EndEnumeration

LoadFont(#Font_WIN0_0,"Consolas", 20)
LoadFont(#Font_WIN0_1,"Consolas", 18)
LoadFont(#Font_WIN0_2,"Consolas", 16)
Global colWin1 = RGB(128,128,255)
Global colWin2 = RGB(64,64,255)
Declare ResizeGadgetsWIN0()

; Declare CheckEve(Event, Window)

Procedure OpenWIN0(x = 0, y = 0, width = 480, height = 390)
  WIN0 = OpenWindow(#PB_Any, x, y, width, height, "Загрузчик программ © SelSoft 2022", #PB_Window_SystemMenu)
  Text_0 = TextGadget(#PB_Any, 0, 100, 480, 40, "Загрузчик программ для ДОН-12")
  SetGadgetFont(Text_0, FontID(#Font_WIN0_0))
  Image_1 = ImageGadget(#PB_Any, 0, 0, 480, 100, ImageID(Img_WIN0_0))
  
  ContainerGadget(10, 0, 140, 480, 50)
  TextGadget(11, 0, 8, 64, 32, "ШАГ1")
  TextGadget(12, 72, 8, 232, 32, "Подключите кабель")
  SetGadgetColor(10, #PB_Gadget_BackColor,RGB(128,128,255))
  SetGadgetColor(11, #PB_Gadget_BackColor,RGB(128,128,255))
  SetGadgetColor(12, #PB_Gadget_BackColor,RGB(128,128,255))
  SetGadgetFont(12, FontID(#Font_WIN0_2))
  SetGadgetFont(11, FontID(#Font_WIN0_1))
  CloseGadgetList()
  
  ContainerGadget(20, 0, 190, 480, 50)
  TextGadget(21, 0, 8, 64, 32, "ШАГ2")
  TextGadget(22, 72, 8, 232, 32, "выберите порт")
  SetGadgetColor(20, #PB_Gadget_BackColor,colWin2)
  SetGadgetColor(21, #PB_Gadget_BackColor,colWin2)
  SetGadgetColor(22, #PB_Gadget_BackColor,colWin2)
  SetGadgetFont(22, FontID(#Font_WIN0_2))
  SetGadgetFont(21, FontID(#Font_WIN0_1))
  CloseGadgetList()
  
  ContainerGadget(30, 0, 240, 480, 50)
  TextGadget(30+1, 0, 8, 64, 32, "ШАГ3")
  TextGadget(30+2, 72, 8, 232, 32, "выберите HEX")
  SetGadgetColor(30, #PB_Gadget_BackColor,colWin1)
  SetGadgetColor(30+1, #PB_Gadget_BackColor,colWin1)
  SetGadgetColor(30+2, #PB_Gadget_BackColor,colWin1)
  SetGadgetFont(30+2, FontID(#Font_WIN0_2))
  SetGadgetFont(30+1, FontID(#Font_WIN0_1))
  CloseGadgetList()
  
    ContainerGadget(40, 0, 290, 480, 50)
  TextGadget(40+1, 0, 8, 64, 32, "ШАГ4")
  TextGadget(40+2, 72, 8, 232, 32, "выберите HEX")
  SetGadgetColor(40, #PB_Gadget_BackColor,colWin2)
  SetGadgetColor(40+1, #PB_Gadget_BackColor,colWin2)
  SetGadgetColor(40+2, #PB_Gadget_BackColor,colWin2)
  SetGadgetFont(40+2, FontID(#Font_WIN0_2))
  SetGadgetFont(40+1, FontID(#Font_WIN0_1))
  CloseGadgetList()
  
  ContainerGadget(50, 0, 340, 480, 50)
  TextGadget(50+1, 0, 8, 64, 32, "ШАГ5")
  TextGadget(50+2, 72, 8, 232, 32, "выберите HEX")
  SetGadgetColor(50, #PB_Gadget_BackColor,colWin1)
  SetGadgetColor(50+1, #PB_Gadget_BackColor,colWin1)
  SetGadgetColor(50+2, #PB_Gadget_BackColor,colWin1)
  SetGadgetFont(50+2, FontID(#Font_WIN0_2))
  SetGadgetFont(50+1, FontID(#Font_WIN0_1))
  CloseGadgetList()  
EndProcedure

Procedure ResizeGadgetsWIN0()
  Protected FormWindowWidth, FormWindowHeight
  FormWindowWidth = WindowWidth(WIN0)
  FormWindowHeight = WindowHeight(WIN0)
  ResizeGadget(Text_0, 0, 80, 480, FormWindowHeight - 350)
  ResizeGadget(Image_1, FormWindowWidth - 480, FormWindowHeight - 100, 480, 80)
EndProcedure

Procedure WIN0_Events(event)
  Select event
    Case #PB_Event_SizeWindow
      ResizeGadgetsWIN0()
    Case #PB_Event_CloseWindow
      ProcedureReturn #False
      
    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect
      
    Case #PB_Event_Gadget
      Select EventGadget()
      EndSelect
    Default
;       CheckEve(event,WIN0)
  EndSelect
  ProcedureReturn #True
EndProcedure

OpenWIN0()

Repeat
  eve = WaitWindowEvent()  
  WIN0_Events(eve)
Until eve = #PB_Event_CloseWindow





; IDE Options = PureBasic 5.73 LTS (Windows - x64)
; CursorPosition = 32
; FirstLine = 13
; Folding = -
; EnableXP